#!/usr/bin/env python3
"""Generate the dbt-style lineage of the query library FROM queries/manifest.json.

Two graphs, both derived purely from the queries and the `system.*` tables they read (their
`reads:` headers) - no external data:
  - sources -> queries : each query (a dbt-style *model*) and the system tables (dbt *sources*) it reads.
  - system-table join graph : which system tables are read TOGETHER in the same query (co-read edges).

Writes lineage/sources.yml, lineage/query_lineage.json, lineage/query_lineage.md.

    python tools/build_lineage.py            # regenerate in place
    python tools/build_lineage.py --check     # exit 1 if any lineage file is stale (CI)

Stdlib only.
"""
from __future__ import annotations

import argparse
import itertools
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "queries" / "manifest.json"
LINEAGE = ROOT / "lineage"


def _mid(x: str) -> str:  # mermaid-safe node id
    return re.sub(r"[^A-Za-z0-9_]", "_", x)


def collect():
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    queries = []                              # (query_id, domain, tier, sorted[reads])
    src2q = defaultdict(list)                 # system table -> [query_id]
    schemas = defaultdict(set)                # system schema -> {table}
    joins = defaultdict(int)                  # frozenset({a,b}) -> co-read count
    for dom in sorted(manifest):
        for e in sorted(manifest[dom], key=lambda e: e["query_id"]):
            reads = sorted({r for r in e["reads"] if r.startswith("system.")})
            queries.append((e["query_id"], dom, e["tier"], reads))
            for r in reads:
                src2q[r].append(e["query_id"])
                parts = r.split(".")
                if len(parts) >= 3:
                    schemas[parts[1]].add(parts[2])
            for a, b in itertools.combinations(reads, 2):
                joins[frozenset((a, b))] += 1
    return queries, {k: sorted(v) for k, v in src2q.items()}, schemas, joins


def render_sources(queries, schemas) -> str:
    read_count = defaultdict(int)
    for _q, _d, _t, reads in queries:
        for r in reads:
            read_count[r] += 1
    out = [
        "# GENERATED by tools/build_lineage.py (do not hand-edit; run: python tools/build_lineage.py).",
        "# dbt-style source defs for the Databricks system tables this library reads.",
        "# `database` is the Unity Catalog `system` catalog.",
        "version: 2",
        "sources:",
    ]
    for schema in sorted(schemas):
        out += [f"  - name: system_{schema}", "    database: system", f"    schema: {schema}", "    tables:"]
        for t in sorted(schemas[schema]):
            n = read_count[f"system.{schema}.{t}"]
            out.append(f"      - name: {t}   # read by {n} quer{'y' if n == 1 else 'ies'}")
    return "\n".join(out) + "\n"


def render_json(queries, src2q, joins) -> str:
    obj = {
        "kind": "query_lineage",
        "note": "Derived purely from queries/manifest.json (the queries' reads: headers). No external data.",
        "summary": {"queries": len(queries), "distinct_sources": len(src2q)},
        "queries": [{"query_id": q, "domain": d, "tier": t, "reads": r} for q, d, t, r in queries],
        "source_index": dict(sorted(src2q.items())),
        "join_graph": [
            {"tables": sorted(pair), "co_read_in_queries": n}
            for pair, n in sorted(joins.items(), key=lambda kv: (-kv[1], sorted(kv[0])))
        ],
    }
    return json.dumps(obj, indent=2) + "\n"


def render_md(queries, src2q, joins) -> str:
    md = [
        "# Query lineage (dbt-style)",
        "",
        "Derived **purely from the queries** and the `system.*` tables their `reads:` headers declare — "
        "no external data. Each query is a dbt-style *model*; each `system.*` table is a *source* "
        "([`sources.yml`](sources.yml)). Machine-readable: [`query_lineage.json`](query_lineage.json).",
        "",
        f"**{len(queries)} queries → {len(src2q)} distinct system-table sources.**",
        "",
        "## Most-read sources",
        "",
        "| System table | # queries |",
        "|---|--:|",
    ]
    for s, v in sorted(src2q.items(), key=lambda kv: (-len(kv[1]), kv[0]))[:15]:
        md.append(f"| `{s}` | {len(v)} |")
    md += ["", "## Lineage graphs (sources → queries), by domain", ""]
    by_dom = defaultdict(list)
    for q, d, t, reads in queries:
        by_dom[d].append((q, reads))
    for dom in sorted(by_dom):
        md += [f"### {dom}", "", "```mermaid", "graph LR"]
        emitted = set()
        for q, reads in sorted(by_dom[dom]):
            for s in reads:
                sid = _mid(s)
                if s not in emitted:
                    md.append(f'  {sid}["{s.replace("system.", "")}"]:::src')
                    emitted.add(s)
                md.append(f"  {sid} --> {_mid(dom + '__' + q)}(\"{q}\")")
        md += ["  classDef src fill:#e8f0fe,stroke:#4285f4;", "```", ""]
    # system-table join graph (co-read)
    md += [
        "## System-table join graph (co-read in the same query)",
        "",
        "Undirected edges = two system tables read together in at least one query (label = how many). "
        "This is the closest thing to *system-table lineage* the queries express — they don't move data "
        "between system tables, they **join** them.",
        "",
        "```mermaid",
        "graph LR",
    ]
    for pair, n in sorted(joins.items(), key=lambda kv: (-kv[1], sorted(kv[0]))):
        a, b = sorted(pair)
        md.append(f'  {_mid(a)}["{a.replace("system.", "")}"] --- |{n}| {_mid(b)}["{b.replace("system.", "")}"]')
    md += ["```", "", "## Reverse index — which queries read each source", "",
           "| System table | Queries |", "|---|---|"]
    for s, v in sorted(src2q.items()):
        md.append(f"| `{s}` | {', '.join(f'`{x}`' for x in v)} |")
    md += [""]
    return "\n".join(md)


FILES = {
    "sources.yml": lambda q, s, sc, j: render_sources(q, sc),
    "query_lineage.json": lambda q, s, sc, j: render_json(q, s, j),
    "query_lineage.md": lambda q, s, sc, j: render_md(q, s, j),
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if any lineage file is stale")
    args = ap.parse_args()
    queries, src2q, schemas, joins = collect()
    rendered = {name: fn(queries, src2q, schemas, joins) for name, fn in FILES.items()}
    if args.check:
        stale = [n for n, text in rendered.items()
                 if not (LINEAGE / n).exists() or (LINEAGE / n).read_text(encoding="utf-8") != text]
        if stale:
            print(f"lineage/ is STALE ({', '.join(stale)}) — run: python tools/build_lineage.py", file=sys.stderr)
            return 1
        print("lineage/ is in sync.")
        return 0
    LINEAGE.mkdir(exist_ok=True)
    for name, text in rendered.items():
        (LINEAGE / name).write_text(text, encoding="utf-8")
    print(f"wrote lineage/ ({len(queries)} queries, {len(src2q)} sources, {len(joins)} join edges)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
